/**
 * Schema barrel file — re-exports all public schemas, types, enums, and constants.
 */

// --- Enums ---
export {
  AutonomyLevel,
  AutonomyMode,
  DecompSessionType,
  DismissalType,
  DroidClientMethod,
  DroidErrorType,
  DroidInteractionMode,
  DroidServerMethod,
  DroidWorkingState,
  FeatureStatus,
  FeatureSuccessState,
  IssueSeverity,
  JsonRpcErrorCode,
  JsonRpcMessageType,
  McpAuthOutcome,
  McpServerStatus,
  McpServerType,
  McpStatus,
  MissionState,
  ModelProvider,
  ProgressLogEntryType,
  ReasoningEffort,
  SessionNotificationType,
  SettingsLevel,
  SkillLocation,
  ToolConfirmationOutcome,
  ToolConfirmationType,
} from './enums.js';

// --- Constants ---
export {
  DEFAULT_REQUEST_TIMEOUT,
  FACTORY_CLIENT_HEADER,
  FACTORY_CLIENT_VERSION,
  FACTORY_PROTOCOL_VERSION,
  JSONRPC_VERSION,
  LEGACY_FACTORY_API_VERSION,
  MCP_AUTH_TIMEOUT,
  SESSION_INIT_TIMEOUT,
} from './constants.js';

// --- Shared (JSON-RPC base) ---
export {
  BaseNotificationSchema,
  BaseRequestSchema,
  BaseResponseFailureSchema,
  BaseResponseSuccessSchema,
  JsonRpcEnvelopeSchema,
  JsonRpcErrorSchema,
  JsonRpcMessageSchema,
  JsonRpcNotificationSchema,
  JsonRpcRequestSchema,
  JsonRpcResponseFailureSchema,
  JsonRpcResponseSchema,
  JsonRpcResponseSuccessSchema,
  TraceContextMetaSchema,
} from './shared.js';

export type {
  BaseNotification,
  BaseRequest,
  BaseResponseFailure,
  BaseResponseSuccess,
  JsonRpcEnvelope,
  JsonRpcError,
  JsonRpcMessage,
  JsonRpcNotification,
  JsonRpcRequest,
  JsonRpcResponse,
  JsonRpcResponseFailure,
  JsonRpcResponseSuccess,
  TraceContextMeta,
} from './shared.js';

// --- Messages (content blocks) ---
export {
  Base64ImageSourceSchema,
  ContentBlockSchema,
  DocumentBlockSchema,
  DocumentSourceSchema,
  FactoryDroidMessageSchema,
  ImageBlockSchema,
  RedactedThinkingBlockSchema,
  TextBlockSchema,
  ThinkingBlockSchema,
  ToolResultBlockSchema,
  ToolUseBlockSchema,
} from './messages.js';

export type {
  Base64ImageSource,
  ContentBlock,
  DocumentBlock,
  DocumentSource,
  FactoryDroidMessage,
  ImageBlock,
  RedactedThinkingBlock,
  TextBlock,
  ThinkingBlock,
  ToolResultBlock,
  ToolUseBlock,
} from './messages.js';

// --- MCP ---
export {
  McpHttpServerConfigFieldsSchema,
  McpRegistryServerSchema,
  McpServerStatusInfoSchema,
  McpSseServerConfigFieldsSchema,
  McpStatusSummarySchema,
  McpStdioServerConfigFieldsSchema,
  McpToolInfoSchema,
  McpToolInputSchemaSchema,
  ToolConfirmationListItemSchema,
} from './mcp.js';

export type {
  McpHttpServerConfigFields,
  McpRegistryServer,
  McpServerStatusInfo,
  McpSseServerConfigFields,
  McpStatusSummary,
  McpStdioServerConfigFields,
  McpToolInfo,
  McpToolInputSchema,
  ToolConfirmationListItem,
} from './mcp.js';

// --- Mission ---
export {
  DiscoveredIssueSchema,
  DismissalRecordSchema,
  FeatureSuccessStateSchema,
  HandoffItemsDismissedEntrySchema,
  HandoffSchema,
  InteractiveCheckSchema,
  MilestoneValidationTriggeredEntrySchema,
  MissionAcceptedEntrySchema,
  MissionFeatureSchema,
  MissionPausedEntrySchema,
  MissionResumedEntrySchema,
  MissionRunStartedEntrySchema,
  ProgressLogEntrySchema,
  SkillDeviationSchema,
  SkillFeedbackSchema,
  TestCaseSchema,
  TestFileSchema,
  TestsSchema,
  VerificationCommandSchema,
  VerificationSchema,
  WorkerCompletedEntrySchema,
  WorkerFailedEntrySchema,
  WorkerPausedEntrySchema,
  WorkerSelectedFeatureEntrySchema,
  WorkerStartedEntrySchema,
} from './mission.js';

export type {
  DiscoveredIssue,
  DismissalRecord,
  Handoff,
  HandoffItemsDismissedEntry,
  InteractiveCheck,
  MilestoneValidationTriggeredEntry,
  MissionAcceptedEntry,
  MissionFeature,
  MissionPausedEntry,
  MissionResumedEntry,
  MissionRunStartedEntry,
  ProgressLogEntry,
  SkillDeviation,
  SkillFeedback,
  TestCase,
  TestFile,
  Tests,
  Verification,
  VerificationCommand,
  WorkerCompletedEntry,
  WorkerFailedEntry,
  WorkerPausedEntry,
  WorkerSelectedFeatureEntry,
  WorkerStartedEntry,
} from './mission.js';

// --- Client (request/response) ---
export {
  AddMcpServerRequestParamsSchema,
  AddMcpServerRequestSchema,
  AddMcpServerResponseSchema,
  AddMcpServerResultSchema,
  AddUserMessageRequestParamsSchema,
  AddUserMessageRequestSchema,
  AddUserMessageResponseSchema,
  AddUserMessageResultSchema,
  AuthenticateMcpServerRequestParamsSchema,
  AuthenticateMcpServerRequestSchema,
  AuthenticateMcpServerResponseSchema,
  AuthenticateMcpServerResultSchema,
  AvailableModelConfigSchema,
  CancelMcpAuthRequestParamsSchema,
  CancelMcpAuthRequestSchema,
  CancelMcpAuthResponseSchema,
  CancelMcpAuthResultSchema,
  ClearMcpAuthRequestParamsSchema,
  ClearMcpAuthRequestSchema,
  ClearMcpAuthResponseSchema,
  ClearMcpAuthResultSchema,
  ClientRequestSchema,
  GitRepoInfoSchema,
  HttpHeaderSchema,
  HttpMcpConfigSchema,
  InitializeSessionRequestParamsSchema,
  InitializeSessionRequestSchema,
  InitializeSessionResponseSchema,
  InitializeSessionResultSchema,
  InterruptSessionRequestParamsSchema,
  InterruptSessionRequestSchema,
  InterruptSessionResponseSchema,
  InterruptSessionResultSchema,
  KillWorkerSessionRequestParamsSchema,
  KillWorkerSessionRequestSchema,
  KillWorkerSessionResponseSchema,
  KillWorkerSessionResultSchema,
  ListMcpRegistryRequestParamsSchema,
  ListMcpRegistryRequestSchema,
  ListMcpRegistryResponseSchema,
  ListMcpRegistryResultSchema,
  ListMcpServersRequestParamsSchema,
  ListMcpServersRequestSchema,
  ListMcpServersResponseSchema,
  ListMcpServersResultSchema,
  ListMcpToolsRequestParamsSchema,
  ListMcpToolsRequestSchema,
  ListMcpToolsResponseSchema,
  ListMcpToolsResultSchema,
  ListSkillsRequestParamsSchema,
  ListSkillsRequestSchema,
  ListSkillsResponseSchema,
  ListSkillsResultSchema,
  LoadSessionRequestParamsSchema,
  LoadSessionRequestSchema,
  LoadSessionResponseSchema,
  LoadSessionResultSchema,
  McpServerConfigSchema,
  MissionSnapshotSchema,
  RemoveMcpServerRequestParamsSchema,
  RemoveMcpServerRequestSchema,
  RemoveMcpServerResponseSchema,
  RemoveMcpServerResultSchema,
  SessionSettingsSchema,
  SessionSourceSchema,
  SessionTagSchema,
  SkillInfoSchema,
  SkillResourceSchema,
  SseMcpConfigSchema,
  StdioMcpConfigSchema,
  SubmitBugReportRequestParamsSchema,
  SubmitBugReportRequestSchema,
  SubmitBugReportResponseSchema,
  SubmitBugReportResultSchema,
  SubmitMcpAuthCodeRequestParamsSchema,
  SubmitMcpAuthCodeRequestSchema,
  SubmitMcpAuthCodeResponseSchema,
  SubmitMcpAuthCodeResultSchema,
  ToggleMcpServerRequestParamsSchema,
  ToggleMcpServerRequestSchema,
  ToggleMcpServerResponseSchema,
  ToggleMcpServerResultSchema,
  ToggleMcpToolRequestParamsSchema,
  ToggleMcpToolRequestSchema,
  ToggleMcpToolResponseSchema,
  ToggleMcpToolResultSchema,
  TokenUsageSchema,
  UpdateSessionSettingsRequestParamsSchema,
  UpdateSessionSettingsRequestSchema,
  UpdateSessionSettingsResponseSchema,
  UpdateSessionSettingsResultSchema,
  WorkerStateInfoSchema,
} from './client.js';

export type {
  AddMcpServerRequest,
  AddMcpServerRequestParams,
  AddMcpServerResponse,
  AddMcpServerResult,
  AddUserMessageRequest,
  AddUserMessageRequestParams,
  AddUserMessageResponse,
  AddUserMessageResult,
  AuthenticateMcpServerRequest,
  AuthenticateMcpServerRequestParams,
  AuthenticateMcpServerResponse,
  AuthenticateMcpServerResult,
  AvailableModelConfig,
  CancelMcpAuthRequest,
  CancelMcpAuthRequestParams,
  CancelMcpAuthResponse,
  CancelMcpAuthResult,
  ClearMcpAuthRequest,
  ClearMcpAuthRequestParams,
  ClearMcpAuthResponse,
  ClearMcpAuthResult,
  ClientRequest,
  GitRepoInfo,
  HttpHeader,
  HttpMcpConfig,
  InitializeSessionRequest,
  InitializeSessionRequestParams,
  InitializeSessionResponse,
  InitializeSessionResult,
  InterruptSessionRequest,
  InterruptSessionRequestParams,
  InterruptSessionResponse,
  InterruptSessionResult,
  KillWorkerSessionRequest,
  KillWorkerSessionRequestParams,
  KillWorkerSessionResponse,
  KillWorkerSessionResult,
  ListMcpRegistryRequest,
  ListMcpRegistryRequestParams,
  ListMcpRegistryResponse,
  ListMcpRegistryResult,
  ListMcpServersRequest,
  ListMcpServersRequestParams,
  ListMcpServersResponse,
  ListMcpServersResult,
  ListMcpToolsRequest,
  ListMcpToolsRequestParams,
  ListMcpToolsResponse,
  ListMcpToolsResult,
  ListSkillsRequest,
  ListSkillsRequestParams,
  ListSkillsResponse,
  ListSkillsResult,
  LoadSessionRequest,
  LoadSessionRequestParams,
  LoadSessionResponse,
  LoadSessionResult,
  McpServerConfig,
  MissionSnapshot,
  RemoveMcpServerRequest,
  RemoveMcpServerRequestParams,
  RemoveMcpServerResponse,
  RemoveMcpServerResult,
  SessionSettings,
  SessionSource,
  SessionTag,
  SkillInfo,
  SkillResource,
  SseMcpConfig,
  StdioMcpConfig,
  SubmitBugReportRequest,
  SubmitBugReportRequestParams,
  SubmitBugReportResponse,
  SubmitBugReportResult,
  SubmitMcpAuthCodeRequest,
  SubmitMcpAuthCodeRequestParams,
  SubmitMcpAuthCodeResponse,
  SubmitMcpAuthCodeResult,
  ToggleMcpServerRequest,
  ToggleMcpServerRequestParams,
  ToggleMcpServerResponse,
  ToggleMcpServerResult,
  ToggleMcpToolRequest,
  ToggleMcpToolRequestParams,
  ToggleMcpToolResponse,
  ToggleMcpToolResult,
  TokenUsage,
  UpdateSessionSettingsRequest,
  UpdateSessionSettingsRequestParams,
  UpdateSessionSettingsResponse,
  UpdateSessionSettingsResult,
  WorkerStateInfo,
} from './client.js';

// --- Server (notifications, permission, ask-user) ---
export {
  AskUserCollectedAnswerSchema,
  AskUserConfirmationDetailsSchema,
  AskUserQuestionSchema,
  AskUserRequestParamsSchema,
  AskUserRequestSchema,
  AskUserResponseSchema,
  AskUserResultSchema,
  ApplyPatchToolConfirmationDetailsSchema,
  AssistantTextDeltaNotificationSchema,
  CliRequestOrNotificationSchema,
  CreateMessageNotificationSchema,
  CreateToolConfirmationDetailsSchema,
  DroidWorkingStateChangedNotificationSchema,
  EditToolConfirmationDetailsSchema,
  ErrorDetailSchema,
  ErrorNotificationSchema,
  ExecuteToolConfirmationDetailsSchema,
  ExitSpecModeConfirmationDetailsSchema,
  McpAuthCompletedNotificationSchema,
  McpAuthRequiredNotificationSchema,
  McpStatusChangedNotificationSchema,
  McpToolConfirmationDetailsSchema,
  MissionFeaturesChangedNotificationSchema,
  MissionHeartbeatNotificationSchema,
  MissionProgressEntryNotificationSchema,
  MissionStateChangedNotificationSchema,
  MissionWorkerCompletedNotificationSchema,
  MissionWorkerStartedNotificationSchema,
  PermissionResolvedNotificationSchema,
  ProposeMissionConfirmationDetailsSchema,
  RequestPermissionRequestParamsSchema,
  RequestPermissionRequestSchema,
  RequestPermissionResponseSchema,
  RequestPermissionResultSchema,
  SessionNotificationParamsSchema,
  SessionNotificationPayloadSchema,
  SessionNotificationSchema,
  SessionNotificationSchemaList,
  SessionTitleUpdatedNotificationSchema,
  SessionTokenUsageChangedNotificationSchema,
  SettingsUpdatedNotificationSchema,
  SettingsUpdatedPayloadSchema,
  StartMissionRunConfirmationDetailsSchema,
  ThinkingTextDeltaNotificationSchema,
  ToolConfirmationDetailsSchema,
  ToolConfirmationInfoSchema,
  ToolProgressUpdateNotificationSchema,
  ToolProgressUpdateSchema,
  ToolResultNotificationSchema,
  ToolUseSchema,
} from './server.js';

export type {
  AskUserCollectedAnswer,
  AskUserConfirmationDetails,
  AskUserQuestion,
  AskUserRequest,
  AskUserRequestParams,
  AskUserResponse,
  AskUserResult,
  ApplyPatchToolConfirmationDetails,
  AssistantTextDeltaNotification,
  CliRequestOrNotification,
  CreateMessageNotification,
  CreateToolConfirmationDetails,
  DroidWorkingStateChangedNotification,
  EditToolConfirmationDetails,
  ErrorDetail,
  ErrorNotification,
  ExecuteToolConfirmationDetails,
  ExitSpecModeConfirmationDetails,
  McpAuthCompletedNotification,
  McpAuthRequiredNotification,
  McpStatusChangedNotification,
  McpToolConfirmationDetails,
  MissionFeaturesChangedNotification,
  MissionHeartbeatNotification,
  MissionProgressEntryNotification,
  MissionStateChangedNotification,
  MissionWorkerCompletedNotification,
  MissionWorkerStartedNotification,
  PermissionResolvedNotification,
  ProposeMissionConfirmationDetails,
  RequestPermissionRequest,
  RequestPermissionRequestParams,
  RequestPermissionResponse,
  RequestPermissionResult,
  SessionNotification,
  SessionNotificationParams,
  SessionNotificationPayload,
  SessionTitleUpdatedNotification,
  SessionTokenUsageChangedNotification,
  SettingsUpdatedNotification,
  SettingsUpdatedPayload,
  StartMissionRunConfirmationDetails,
  ThinkingTextDeltaNotification,
  ToolConfirmationDetails,
  ToolConfirmationInfo,
  ToolProgressUpdate,
  ToolProgressUpdateNotification,
  ToolResultNotification,
  ToolUse,
} from './server.js';
